language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
bundler_args: --jobs=2
script: CODECLIMATE_REPO_TOKEN=8e9db6ee5f3818e87287a6393086c2ccb9b1b83106c5bfb972211abefd2fe162 bundle exec rspec --tag category:verbose && bundle exec rspec
branches:
  only:
    - master
notifications:
  email: false
matrix:
  allow_failures:
    - rvm: 2.2
    - rvm: ruby-head
