unmarked:
  girls:
  - &cure_black
    human_name:   美墨なぎさ
    precure_name: キュアブラック
  - &cure_white
    human_name:   雪城ほのか
    precure_name: キュアホワイト
max_heart:
  girls:
  - <<: *cure_black
  - <<: *cure_white
  - human_name:   九条ひかり
    precure_name: シャイニールミナス
splash_star:
"yes":
yes_gogo:
flesh:
heart_catch:
suite:
smile:
  title: スマイルプリキュア！
  started_date: 2012-02-05
  ended_date:   2013-01-27
  common_transform_message: |
    プリキュアスマイルチャージ！
  girls:
  - human_name:   星空みゆき
    precure_name: キュアハッピー
    transform_message:
    - |
      GO! GO! Let's GO ハッピー！
      キラキラ輝く未来の光！ キュアハッピー！
    extra_names:
    - プリンセスハッピー
    - ウルトラハッピー
  - human_name:   日野あかね
    precure_name: キュアサニー
    transform_message: |
      GO! GO! Let's GO サニー！
      太陽サンサン熱血パワー！ キュアサニー！
    extra_names:
    - プリンセスサニー
    - ウルトラサニー
  - human_name:   黄瀬やよい
    precure_name: キュアピース
    transform_message: |
      GO! GO! Let's GO ピース！
      ピカピカピカリンジャンケンポン！ キュアピース！
    extra_names:
    - プリンセスピース
    - ウルトラピース
  - human_name:   緑川なお
    precure_name: キュアマーチ
    transform_message: |
      GO! GO! Let's GO マーチ！
      勇気リンリン直球勝負！ キュアマーチ！
    extra_names:
    - プリンセスマーチ
    - ウルトラマーチ
  - human_name:   青木れいか
    precure_name: キュアビューティ
    transform_message: |
      GO! GO! Let's GO ビューティ！
      しんしんと降り積もる清き心！ キュアビューティ！
    extra_names:
    - プリンセスビューティ
    - ウルトラビューティ
dokidoki:
  title: ドキドキ！プリキュア
  started_date: 2013-02-03
  ended_date:   2014-01-26
  common_transform_message: |
    プリキュアラブリンク！
    L! O! V! E!
  girls:
  - human_name:   相田マナ
    precure_name: キュアハート
    transform_message: |
      みなぎる愛！ キュアハート！
      愛を無くした悲しいジコチューさん、
      このキュアハートがあなたのドキドキ取り戻してみせる！
#    extra_names:
  - human_name:   菱川六花
    precure_name: キュアダイヤモンド
    transform_message: |-
      英知の光！ キュアダイヤモンド！
      人の思いを踏みにじるなんて許せない、
      このキュアダイヤモンドがあなたの頭を冷やしてあげる！
#    extra_names:
  - human_name:   四葉ありす
    precure_name: キュアロゼッタ
    transform_message: |
      ひだまりポカポカ キュアロゼッタ！
      世界を制するのは愛だけです、
      さぁ、あなたも私と愛を育んでくださいな
#    extra_names:
  - human_name:   剣崎真琴
    precure_name: キュアソード
    transform_message: |
      勇気の刃！ キュアソード！
      このキュアソードが愛の剣で
      あなたの野望を断ち切ってみせる！
#    extra_names:
  - human_name:   円亜久里
    precure_name: キュアエース
    transform_message: |
      愛の切り札！ キュアエース！
      美しさは正義の証し、ウインク一つで、
      あなたのハートを射抜いて差し上げますわ
#    extra_names:
happiness_charge:
  title: ハピネスチャージプリキュア！
#  started_date: 2014-02-
#  ended_date:   2015-01-
#  girls:
#  - human_name:
#    precure_name: キュア
#    transform_message: |-
#
#    extra_names:
