unmarked:
  - &cure_black
    human_name:   美墨なぎさ
    precure_name: キュアブラック
  - &cure_white
    human_name:   雪城ほのか
    precure_name: キュアホワイト
max_heart:
  - <<: *cure_black
  - <<: *cure_white
  - human_name:   九条ひかり
    precure_name: シャイニールミナス
splash_star:
"yes":
yes_gogo:
flesh:
heart_catch:
suite:
smile:
  title: スマイルプリキュア！
  started_date: 2012-02-05
  ended_date:   2013-01-27
  girls:
  - human_name:   星空みゆき
    precure_name: キュアハッピー
  - human_name:   日野あかね
    precure_name: キュアサニー
  - human_name:   黄瀬やよい
    precure_name: キュアピース
    transform_serif: |-
      プリキュアスマイルチャージ！
      GO! GO! Let's GO ピース！
      ピカピカピカリンジャンケンポン！ キュアピース！
    extra_names:
    - プリンセスピース
      ウルトラピース
  - human_name:   緑川なお
    precure_name: キュアマーチ
  - human_name:   青木れいか
    precure_name: キュアビューティ
dokidoki:
happiness_charge:
