unmarked:
  title: ふたりはプリキュア
  started_date: 2004-02-01
  ended_date:   2005-01-30
  before_transform_message: |
    デュアル・オーロラ・ウェイブ！！
  after_transform_message: |
    ふたりはプリキュア！
    闇の力のしもべ達よ！
    とっととお家に帰りなさい！
  girls:
  - cure_black
  - cure_white

max_heart:
  title: ふたりはプリキュア Max Heart
  started_date: 2005-02-06
  ended_date:   2006-01-29
  before_transform_message: |
    デュアル・オーロラ・ウェイブ！！
  after_transform_message: |
    ふたりはプリキュア！
    闇の力のしもべ達よ！
    とっととお家に帰りなさい！
  girls:
  - cure_black
  - cure_white
  - shiny_luminous

splash_star:
  title: ふたりはプリキュア Splash Star
  started_date: 2006-02-05
  ended_date:   2007-01-28
  before_transform_message: |
    デュアル・スピリチュアル・パワー！
  after_transform_message: |
    ふたりはプリキュア！
    聖なる泉を汚す者よ！
    阿漕な真似はお止めなさい！
  girls:
  - cure_bloom
  - cure_egret

"yes":
  title: Yes！ プリキュア5
  started_date: 2007-02-04
  ended_date:   2008-01-27
  before_transform_message: |
    プリキュア！メタモルフォーゼ！
  after_transform_message: |
    希望の力と未来の光！
    華麗に羽ばたく5つの心！
    Yes！プリキュア5！
  girls:
  - cure_dream
  - cure_rouge
  - cure_lemonade
  - cure_mint
  - cure_aqua

yes_gogo:
  title: Yes！ プリキュア5 Go Go！
  started_date: 2008-02-03
  ended_date:   2009-01-25
  before_transform_message: |
    プリキュア！メタモルフォーゼ！
  after_transform_message: |
    希望の力と未来の光！
    華麗に羽ばたく5つの心！
    Yes！プリキュア5！
  girls:
  - cure_dream
  - cure_rouge
  - cure_lemonade
  - cure_mint
  - cure_aqua
  - milky_rose
flesh:
  title: フレッシュプリキュア！
  started_date: 2009-02-01
  ended_date:   2010-01-31
  before_transform_message: |
    チェインジ！プリキュア・ビートアップ！
  after_transform_message: |
    レッツプリキュア！
  girls:
  - cure_peach
  - cure_berry
  - cure_pine
  - cure_passion

heart_catch:
  title: ハートキャッチプリキュア！
  started_date: 2010-02-07
  ended_date:   2011-01-30
  before_transform_message: |
    (プリキュアの種、いくですぅ！)
    プリキュア！オープンマイハート！
  after_transform_message: |
    ハートキャッチ、プリキュア！
  girls:
  - cure_blossom
  - cure_marine
  - cure_sunshine
  - cure_moonlight

suite:
  title: スイートプリキュア♪
  started_date: 2011-02-06
  ended_date:   2012-01-29
  before_transform_message: |
    レッツプレイ！プリキュアモジュレーション！！
  after_transform_message: |
    響け4人の組曲！スイートプリキュア！
  girls:
  - cure_melody
  - cure_rhythm
  - cure_beat
  - cure_muse

smile:
  title: スマイルプリキュア！
  started_date: 2012-02-05
  ended_date:   2013-01-27
  before_transform_message: |
    (レディ？)
    プリキュア・スマイルチャージ！
  after_transform_message: |
    5つの光が導く未来！
    輝け！スマイルプリキュア！
  girls:
  - cure_happy
  - cure_sunny
  - cure_peace
  - cure_march
  - cure_beauty

dokidoki:
  title: ドキドキ！プリキュア
  started_date: 2013-02-03
  ended_date:   2014-01-26
  before_transform_message: |
    プリキュアラブリンク！
    L! O! V! E!
  after_transform_message: |
    響け愛の鼓動！ドキドキプリキュア！
  girls:
  - cure_heart
  - cure_diamond
  - cure_rosetta
  - cure_sword
  - cure_ace

#happiness_charge:
#  title: ハピネスチャージプリキュア！
#  started_date: 2014-02-
#  ended_date:   2015-01-
#  common_transform_message: |
#
#  girls:
#  - cure_lovely
#  - cure_princess
