unmarked:
max_heart:
splash_star:
"yes":
yes_gogo:
flesh:
heart_catch:
suite:
smile:
  title: スマイルプリキュア！
  girls:
  - human_name:   星空みゆき
    precure_name: キュアハッピー
  - human_name:   日野あかね
    precure_name: キュアサニー
  - human_name:   黄瀬やよい
    precure_name: キュアピース
    transform_serif: ピカピカピカリンジャンケンポン！ キュアピース！
    extra_names:
    - プリンセスピース
      ウルトラピース
  - human_name:   緑川なお
    precure_name: キュアマーチ
  - human_name:   青木れいか
    precure_name: キュアビューティ
dokidoki:
happiness_charge:
