futari_wa_pretty_cure:             unmarked
futari_wa_pretty_cure_max_heart:   max_heart
futari_wa_pretty_cure_splash_star: splash_star
yes_precure_five:                  "yes"
yes_precure5:                      "yes"
yes_precure_five_gogo:             yes_gogo
yes_precure5_gogo:                 yes_gogo
flesh_precure:                     flesh
heart_catch_precure:               heart_catch
suite_precure:                     suite
smile_precure:                     smile
dokidoki_precure:                  dokidoki
happiness_charge_precure:          happiness_charge
